FROM debian:stretch

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    ca-certificates curl file git wget unzip \
    build-essential \
    autoconf automake cmake libssl-dev pkg-config autotools-dev libtool xutils-dev && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/nvm
ENV NVM_DIR=/usr/local/nvm
ENV NODE_VERSION=14.15.0
RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
RUN npm install -g yarn

WORKDIR /app
RUN wget https://github.com/Daemon-Technologies/Mining-Bot/releases/download/1.0.0/Mining-Bot_V1.0.0_linux.zip
RUN unzip Mining-Bot_V1.0.0_linux.zip
WORKDIR /app/Mining-Bot_V1.0.0_linux
RUN wget -O stacks-node https://github.com/Daemon-Technologies/Mining-Bot/releases/download/1.0.0/stacks-node-linux
RUN yarn install
ENTRYPOINT yarn start