version: '3.7'

services:

  mining_server:
    build:
      context: .
      dockerfile: Dockerfile_mining_server
    ports:
      - "5000:5000"
      - "20443:20443"
      - "20444:20444"
      - "8000:8000"
    networks:
      - stacks

networks:
  stacks:
    driver: bridge